name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published, edited ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ZiggyAlloc.sln
      
    - name: Build
      run: dotnet build --no-restore --configuration Release ZiggyAlloc.sln
      
    - name: Test
      run: |
        echo "Runner architecture: $RUNNER_ARCH"
        echo "uname -m: $(uname -m)"
        echo "uname -p: $(uname -p)"

        # Run tests with improved error handling and cleanup
        echo "Running stable test suite"

        # Check if running on ARM64 and adjust test settings accordingly
        if [[ "$RUNNER_ARCH" == "ARM64" || "$(uname -m)" == "arm64" ]]; then
          echo "ARM64 detected - running tests with reduced parallelism to prevent memory issues"
          dotnet test --no-build --configuration Release --verbosity normal tests/ZiggyAlloc.Tests.csproj --settings tests/arm64.runsettings --logger "console;verbosity=normal" --logger "trx;LogFileName=test-results.trx" --blame --blame-hang-timeout 30s || {
            echo "Tests completed with potential issues - checking results..."
            if [ -f "tests/TestResults/test-results.trx" ]; then
              echo "Test results file exists - checking for failures..."
            fi
            exit 1
          }
        else
          echo "Non-ARM64 architecture - running tests with normal settings"
          dotnet test --no-build --configuration Release --verbosity normal tests/ZiggyAlloc.Tests.csproj --logger "console;verbosity=normal" --logger "trx;LogFileName=test-results.trx" || {
            echo "Tests completed with potential issues - checking results..."
            if [ -f "tests/TestResults/test-results.trx" ]; then
              echo "Test results file exists - checking for failures..."
            fi
            exit 1
          }
        fi

        # Additional error handling and cleanup
        echo "Performing cleanup and checking for any remaining processes..."
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          taskkill /f /im dotnet.exe 2>/dev/null || true
          taskkill /f /im testhost.exe 2>/dev/null || true
        else
          pkill -f dotnet 2>/dev/null || true
          pkill -f testhost 2>/dev/null || true
        fi

        # Collect crash dumps on ARM64 for debugging
        if [[ "$RUNNER_ARCH" == "ARM64" || "$(uname -m)" == "arm64" ]]; then
          echo "ARM64 detected - collecting crash dumps for analysis..."
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            # Create crash dump directory
            mkdir -p crash-dumps
            # Try to collect any core dumps
            if [ -d "/var/lib/systemd/coredump" ]; then
              cp /var/lib/systemd/coredump/* crash-dumps/ 2>/dev/null || true
            fi
            # List any crash dump files
            ls -la crash-dumps/ 2>/dev/null || echo "No crash dumps found"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # On macOS, check for crash reports
            mkdir -p crash-dumps
            if [ -d "$HOME/Library/Logs/DiagnosticReports" ]; then
              cp "$HOME/Library/Logs/DiagnosticReports"/* crash-dumps/ 2>/dev/null || true
            fi
            ls -la crash-dumps/ 2>/dev/null || echo "No crash dumps found"
          fi
        fi

        # Upload crash dumps as artifacts for ARM64 debugging
        if [[ "$RUNNER_ARCH" == "ARM64" || "$(uname -m)" == "arm64" ]]; then
          if [ -d "crash-dumps" ] && [ "$(ls -A crash-dumps 2>/dev/null)" ]; then
            echo "Uploading crash dumps for analysis..."
            # Create a unique name for the artifact
            ARTIFACT_NAME="crash-dumps-${RUNNER_OS}-${GITHUB_RUN_ID}"
            # Note: In a real scenario, you would use actions/upload-artifact@v4 here
            echo "Crash dumps would be uploaded with name: $ARTIFACT_NAME"
          fi
        fi

    - name: Test Debug Tests (Allow Failures)
      run: |
        echo "Running debug tests (these are allowed to crash)"
        dotnet test --no-build --configuration Release --verbosity normal tests/DebugTests/ZiggyAlloc.DebugTests.csproj || echo "Debug tests completed (some expected crashes occurred)"
      continue-on-error: true

    - name: Run examples
      run: dotnet run --project examples/Examples.csproj --configuration Release

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'edited')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Restore dependencies
      run: dotnet restore ZiggyAlloc.sln
      
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.VERSION }} ZiggyAlloc.sln
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release --output ./artifacts -p:Version=${{ steps.version.outputs.VERSION }} -p:IncludeContentInPack=true ZiggyAlloc.Main.csproj
      
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg

  # Auto-assign reviewers for PRs
  assign-reviewers:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Auto-assign reviewers
      uses: kentaro-m/auto-assign-action@v1.2.5
      with:
        configuration-path: '.github/auto-assign.yml'